project:
  type: website

website:
  title: "Jimena Del Pozo"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Resume
        href: resume.qmd
      - text: Projects
        href: projects.qmd
      - text: Skills
        href: skills.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    theme: flatly
    toc: true
    number-sections: true
    css: styles.css
